"""messages

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-10 08:06:26.932588

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("gmail_id", sa.Text(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sender_domain", sa.Text(), nullable=True),
        sa.Column("auth_result", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "fetched",
                "unverified",
                "not_txn",
                "pending_classification",
                "extracted",
                "needs_review",
                "failed",
                name="message_status",
            ),
            server_default="fetched",
            nullable=False,
        ),
        sa.Column("pipeline_version", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("gmail_id", name=op.f("uq_messages_gmail_id")),
    )
    op.create_index(op.f("ix_messages_received_at"), "messages", ["received_at"], unique=False)
    op.create_index(op.f("ix_messages_status"), "messages", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_status"), table_name="messages")
    op.drop_index(op.f("ix_messages_received_at"), table_name="messages")
    op.drop_table("messages")
    # ### end Alembic commands ###
    # Autogenerate drops the table but not the enum type it created; without this a
    # downgrade + upgrade fails with 'type "message_status" already exists'.
    sa.Enum(name="message_status").drop(op.get_bind(), checkfirst=True)
