"""sender registry

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-10 13:11:48.543778

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sender_registry",
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("learned", "approved", "blocked", name="sender_status"),
            nullable=False,
        ),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("txn_count", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "domain = lower(domain)", name=op.f("ck_sender_registry_domain_lowercase")
        ),
        sa.PrimaryKeyConstraint("domain", name=op.f("pk_sender_registry")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sender_registry")
    # ### end Alembic commands ###
    # drop_table leaves the enum type behind (same trap as 0002).
    sa.Enum(name="sender_status").drop(op.get_bind(), checkfirst=True)
